[package]
name = "assemble"
version = "0.1.0"
authors = ["nsmryan <nsmryan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wrapped2d = "0.4"
sdl2 = { version = "0.32", features = ["image"] }
